### ISSUE TITLE
start is not disconnect

### ISSUE THREAD

**Issue by garybuhrmaster** [simontelephonics/gvsip.info#1]
Minor nit.  GV did not state it will disconnect XMPP service on June 18th, they stated they would start the processes then.  Typically, that means that even if they stick to the date (and I have no idea as to whether they will stick to that date, XMPP has been declared dead more than once before) there will be a period of time when it may work, or not work, or work intermittently, for individuals as the changes migrate through their infrastructure.  Of course, if you have better information that they will actually complete the disconnect on June 18th, please close this issue.  I am not sure of the best wording to make it clear that those have been using GV via XMPP should be well into their planning cycle for moving forward.  Perhaps something like rather than "would be discontinued on" to "is scheduled to start to end operations on"?

**Comment by billsimon** [comment]
The announcement reads "starting on ... we will finish" which makes no sense. I acknowledge interpreting this confusing statement in a certain way but will instead quote their statement and leave the interpretation up to the reader.
