### ISSUE TITLE
Request- OAuth from Goopgle Login 

### ISSUE THREAD

**Issue by markosjal** [simontelephonics/gvsip.info#6]
Was wondering if someone (Bill?) might share OAuth by way of Google Login much like on Simonics.com? I have been trying to figure this out with no luck.

Any code samples would be appreciated , but specifically calling to the Google Auth and in your Simonics example the code in authorize.php and deauthorize.php. If your killing the Simonics gateway this might be useful to others! I do not care much how you process the refresh_token I have planned a method for that already.

It seems this is a far better way to get the refresh_token than the playground.
Thanks

Mark

**Comment by billsimon** [comment]
I did the authn/z for simonics.com using OpenID Connect. 

Google's documentation: https://developers.google.com/identity/protocols/OpenIDConnect

PHP library I used (rest of WordPress-based site is PHP): https://github.com/jumbojett/OpenID-Connect-PHP

As far as getting the oauth2 token for GV-SIP implementation, setting up a site is a lot more work than simply plugging your credentials into Google's oauth2 playground.

**Comment by markosjal** [comment]
The problem is a non-technical user using the playground is not a good way to do it.

**Comment by billsimon** [comment]
Depending on your interests, you might also find https://github.com/google/oauth2l to be useful. You can get tokens through a command line instead of the playground or a web app. 

Closing this ticket as it's not related to gvsip.
