### ISSUE TITLE
Any futur solution ?

### ISSUE THREAD

**Issue by intika** [simontelephonics/gvsip.info#8]
Hi,

First thank you for maintaining gvgw the service was amazing and we are all missing it

After digging a little bit apparently the only available service alternative is pbxes.com but as i saw some users complaining about it i don't think the service is good right now 

There is also a hacky alternative https://hobbiesbytwinclouds.wordpress.com/2018/05/27/how-to-make-and-receive-calls-using-google-voice-without-xmpp-may-2018-revision/ but it does not seem reliable nor secure

I just have a simple question is there a possibility/alternative to to have a reliable sip-gw or the thing is dead for good ? 

I guess you have been asked this question a lot... so sorry if... 

Thanks a lot !

and what about 
https://github.com/naf419/asterisk/tree/gvsip ? (is not that a possible way to get gvgw back even if it's not as cheap as before ?)

**Comment by billsimon** [comment]
The Asterisk solution is documented here on gvsip.info and does not require the naf patches any longer if you use Asterisk master branch.
